version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - zip -r my-fastapi-app.zip .
artifacts:
  files:
    - my-fastapi-app.zip
  discard-paths: yes